'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { cn } from '@/app/lib/utils';
import { Container } from '../ui/container';

// hover:bg-green-200/30
// hover:bg-purple-200/30
// hover:bg-amber-100/30
// hover:bg-rose-100/50
// hover:bg-slate-200/30
// hover:bg-orange-200/30

const FEATURES = [
  {
    id: 'fan-royalties',
    title: 'Fan Royalties',
    subtitle: 'Get paid to listen',
    description:
      'Earn $0.05 per stream. The first platform to pay you for engagement.',
    details:
      'Unlike any other platform, SMASH pays listeners. 3% of all gross programmatic advertising revenue is distributed back to fans who engage with music. This creates a circular economy where your time and attention are valued assets, not just products to be sold.',
    stat: '3%',
    statLabel: 'Revenue Share',
    color: 'bg-orange-200/30',
    videoUrl: '/videos/headphones.mp4',
  },
  {
    id: 'artist-payouts',
    title: 'Artist Payouts',
    subtitle: '$0.10 per stream',
    description: 'Fair compensation for creators. 10x the industry average.',
    details:
      "We prioritize creators with a $0.10 payout per stream compared to Spotify's ~$0.003. By cutting out intermediaries and using blockchain for transparent accounting, artists get paid what they deserve, instantly.",
    color: 'bg-purple-200/30',
    imageUrl: '/images/money-up.png',
  },
  {
    id: 'viral-growth',
    title: 'Viral Referrals',
    subtitle: 'Get paid to share',
    description: '2% Royalty for sharing music and bringing friends.',
    details:
      "Our viral growth engine rewards you for expanding the community. Receive a 2% royalty on revenue generated by users you refer. It's not just an affiliate link; it's an ownership stake in the network's growth.",
    color: 'bg-amber-100/30',
    videoUrl: '/videos/cards.mp4',
  },
  {
    id: 'token-utility',
    title: 'SMASH Token',
    subtitle: 'Unified Economy',
    description: 'Governance, Staking, and Spending power.',
    details:
      'SMASH COIN is the lifeblood of the ecosystem. Use it to buy merch, concert tickets, and ad space, or stake it to earn higher royalty tiers and vote on platform governance. A true utility token with real-world value.',
    color: 'bg-rose-100/50',
    imageUrl: '/images/coin.png',
  },
  {
    id: 'ad-revenue',
    title: 'Ad Revenue',
    subtitle: 'Programmatic Model',
    description: '$1.50 - $4.00 CPM driving sustainability.',
    details:
      'Our economic model is grounded in reality. High-value audio and display programmatic ads generate the revenue that fuels the ecosystem. As user attention grows, so does the revenue pool shared with everyone.',
    color: 'bg-slate-200/30',
    videoUrl: '/videos/circles.mp4',
  },
  {
    id: 'transparency',
    title: 'Transparency',
    subtitle: 'On-Chain Records',
    description: 'Trustless accounting via blockchain.',
    details:
      'Say goodbye to black box accounting. Every stream, every ad impression, and every payout is recorded on-chain. Artists and fans can verify revenue flows in real-time, ensuring total trust and accountability.',
    color: 'bg-green-200/30',
    imageUrl: '/images/circles.png',
  },
];

export function EconomicsAccordion() {
  const [selectedId, setSelectedId] = useState<string | null>('fan-royalties');

  // Split features into rows of 3 for desktop layout
  const rows = [];
  for (let i = 0; i < FEATURES.length; i += 3) {
    rows.push(FEATURES.slice(i, i + 3));
  }

  return (
    <section>
      <Container className="flex flex-col gap-6">
        {rows.map((row, rowIndex) => {
          // Check if any item in this row is selected
          const isRowActive = row.some((feature) => feature.id === selectedId);
          const activeFeature = FEATURES.find((f) => f.id === selectedId);

          return (
            <div key={rowIndex} className="contents">
              {/* The Grid Row */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {row.map((feature) => {
                  const isSelected = selectedId === feature.id;
                  return (
                    <motion.div
                      key={feature.id}
                      layoutId={`card-${feature.id}`}
                      onClick={() =>
                        setSelectedId(isSelected ? null : feature.id)
                      }
                      className={cn(
                        'relative cursor-pointer bg-gray-50/50 border border-gray-300 overflow-hidden rounded-2xl p-6 transition-all duration-300',
                        isSelected && feature.color,
                        `hover:${feature.color}`,
                      )}>
                      <div className="flex justify-between items-start mb-4">
                        <img
                          src="/icons/logo.svg"
                          alt="SMASH"
                          className="size-10"
                        />
                        <div className="transition-transform duration-500 bg-gray-50 size-10 rounded-lg border border-gray-200">
                          <ChevronDown
                            className={cn(
                              'size-full p-2 text-muted-foreground transition-transform duration-500',
                              isSelected ? 'rotate-180' : 'rotate-0',
                            )}
                          />
                        </div>
                      </div>

                      <h3 className="text-xl font-bold mb-2">
                        {feature.title}
                      </h3>
                      <p className="text-sm text-muted-foreground line-clamp-2">
                        {feature.description}
                      </p>
                    </motion.div>
                  );
                })}
              </div>

              {/* The Expansion Panel - Rendered ONLY if this row contains the selected item */}
              <AnimatePresence mode="wait">
                {isRowActive && activeFeature && (
                  <motion.div
                    key={activeFeature.id}
                    initial={{ opacity: 0, height: 0, y: -20 }}
                    animate={{ opacity: 1, height: 'auto', y: 0 }}
                    exit={{ opacity: 0, height: 0, y: -20 }}
                    transition={{ duration: 0.4, ease: 'easeInOut' }}
                    className="overflow-hidden w-full">
                    <div
                      className={cn(
                        'relative w-full mt-6 rounded-3xl border border-gray-300 p-8 md:p-12 overflow-hidden',
                        activeFeature.color,
                      )}>
                      <div className="relative z-10 grid md:grid-cols-2 gap-12 items-center">
                        <div>
                          <h3 className="text-3xl md:text-5xl font-bold mb-6">
                            {activeFeature.title}
                          </h3>

                          <p className="text-lg text-muted-foreground mb-8 leading-relaxed">
                            {activeFeature.details}
                          </p>
                        </div>

                        <div className="relative h-[300px] md:h-[400px] rounded-2xl border border-white/10 flex flex-col items-center justify-center overflow-hidden group">
                          {activeFeature.imageUrl ? (
                            <img
                              src={activeFeature.imageUrl || '/images/1.png'}
                              alt="SMASH"
                              className="size-full object-cover"
                            />
                          ) : (
                            <video
                              src={activeFeature.videoUrl}
                              autoPlay
                              muted
                              loop
                              className="size-full object-cover"
                            />
                          )}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </Container>
    </section>
  );
}
